export const brainHealthTips: string[] = [
    "Just 30 minutes of moderate exercise a day can improve memory and cognitive function.",
    "A diet rich in Omega-3 fatty acids, found in fish like salmon, can support brain health.",
    "Challenge your mind daily with puzzles, games, or by learning a new skill.",
    "Quality sleep is crucial for memory consolidation. Aim for 7-9 hours per night.",
    "Staying socially active can help reduce the risk of cognitive decline.",
    "Mindfulness meditation can reduce stress and improve focus and attention.",
    "Chronic stress can damage brain cells. Practice relaxation techniques like deep breathing.",
    "Berries, nuts, and leafy green vegetables are packed with brain-boosting antioxidants.",
    "Learning a musical instrument can enhance coordination, memory, and concentration.",
    "Stay hydrated. Dehydration can lead to confusion and memory problems.",
    "Laughter is great for your brain. It releases endorphins and reduces stress hormones.",
    "Take short breaks during work or study to rest your mind and improve productivity.",
    "Deep breathing exercises can increase oxygen supply to your brain and promote calmness.",
    "Visualization techniques, where you imagine a peaceful scene, can significantly relieve tension.",
    "Progressive muscle relaxation, tensing and then relaxing muscle groups, can ease physical stress.",
    "Limit multitasking. Focusing on one task at a time can improve concentration and reduce errors.",
    "Spending time in nature has been shown to lower stress levels and improve mental clarity.",
    "Keep a journal. Writing down your thoughts can help you process emotions and reduce stress.",
    "The 'Pomodoro Technique'—working for 25 minutes, then taking a 5-minute break—can boost focus.",
    "A balanced diet stabilizes your mood. Avoid high-sugar snacks that cause energy crashes.",
    "Teaching someone else a skill you know is a powerful way to reinforce your own learning.",
    "Aerobic exercise, like running or swimming, stimulates the growth of new neurons.",
    "Protect your head. Always wear a helmet during activities like cycling or skating.",
    "Manage your blood pressure. High blood pressure is linked to a higher risk of cognitive decline.",
    "Volunteering can provide a sense of purpose and social connection, both vital for brain health.",
    "Creative hobbies like painting or writing can improve brain plasticity and problem-solving skills.",
    "Limit your intake of processed foods and sugary drinks to protect your brain from inflammation.",
    "Listening to new and complex music can be a workout for your brain's auditory centers.",
    "Daydreaming isn't a waste of time. It can boost creativity and problem-solving.",
    "A simple walk can spark creative thinking. Many great thinkers were avid walkers."
];
